name: WordPress Plugin Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: PHP 8.1 Test
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Copy PHPUnit config
        run: |
          if [ ! -f "phpunit.xml" ]; then
            cp phpunit.xml.dist phpunit.xml
          fi

      - name: Set up WordPress Test Environment
        run: |
          # Set up directories
          export WP_TESTS_DIR=/tmp/wordpress-tests-lib
          export WP_CORE_DIR=/tmp/wordpress
          mkdir -p $WP_TESTS_DIR
          mkdir -p $WP_CORE_DIR

          # Download WordPress
          wget -q https://wordpress.org/wordpress-6.4.zip
          unzip -q wordpress-6.4.zip
          mv wordpress/* $WP_CORE_DIR/

          # Download WordPress Test Suite
          wget -q https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/ -P $WP_TESTS_DIR --recursive
          wget -q https://develop.svn.wordpress.org/trunk/tests/phpunit/data/ -P $WP_TESTS_DIR --recursive

          # Create wp-tests-config.php
          cd $WP_TESTS_DIR
          wget -q https://raw.github.com/wp-cli/wp-cli/master/templates/wp-tests-config.php -O wp-tests-config.php
          
          # Configure test environment
          sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
          sed -i "s|localhost|127.0.0.1:3306|" wp-tests-config.php

          # Add additional configuration
          echo "define( 'WP_TESTS_DOMAIN', 'example.org' );" >> wp-tests-config.php
          echo "define( 'WP_TESTS_EMAIL', 'admin@example.org' );" >> wp-tests-config.php
          echo "define( 'WP_TESTS_TITLE', 'Test Blog' );" >> wp-tests-config.php
          echo "define( 'WP_PHP_BINARY', 'php' );" >> wp-tests-config.php
          echo "define( 'WPLANG', '' );" >> wp-tests-config.php

          # Copy bootstrap file
          cd $WP_TESTS_DIR
          cp includes/bootstrap.php ./

          # Set environment variables
          echo "WP_TESTS_DIR=$WP_TESTS_DIR" >> $GITHUB_ENV
          echo "WP_CORE_DIR=$WP_CORE_DIR" >> $GITHUB_ENV

      - name: Run tests
        run: composer test

      - name: Store test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/_output
          retention-days: 5